package:
  format-version: "1.0.0"
  name: "wireless_apps_rnwf"
  type: "application"
  status: "production"
  required: false
  version: "v3.1.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.23.0"
    - name: "core"
      type: "package"
      version: "v3.15.5"
    - name: "bsp"
      type: "package"
      version: "v3.23.0"
    - name: "wireless_wifi"
      type: "package"
      version: "v3.12.2"
    - name: "wireless_system_rnwf"
      type: "package"
      version: "v3.1.0"